apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops-app
  namespace: {{ .Values.namespace }}
  labels:
    app: devops-app
spec:
  replicas: {{ .Values.app.replicaCount }}
  selector:
    matchLabels:
      app: devops-app
  template:
    metadata:
      labels:
        app: devops-app
    spec:
      containers:
        - name: app
          image: "{{ .Values.app.image.repository }}:{{ .Values.app.image.tag }}"
          ports:
            - containerPort: {{ .Values.app.containerPort }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops-nginx
  namespace: {{ .Values.namespace }}
  labels:
    app: devops-nginx
spec:
  replicas: {{ .Values.nginx.replicaCount }}
  selector:
    matchLabels:
      app: devops-nginx
  template:
    metadata:
      labels:
        app: devops-nginx
    spec:
      containers:
        - name: nginx
          image: "{{ .Values.nginx.image.repository }}:{{ .Values.nginx.image.tag }}"
          ports:
            - containerPort: {{ .Values.nginx.containerPort }}
