apiVersion: v1
kind: Service
metadata:
  name: app
  namespace: {{ .Values.namespace }}
  labels:
    app: app
spec:
  selector:
    app: devops-app
  ports:
    - name: http
      protocol: TCP
      port: {{ .Values.app.containerPort }}
      targetPort: {{ .Values.app.containerPort }}
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: nginx
  namespace: {{ .Values.namespace }}
  labels:
    app: nginx
spec:
  selector:
    app: devops-nginx
  ports:
    - name: http
      protocol: TCP
      port: {{ .Values.nginx.containerPort }}
      targetPort: {{ .Values.nginx.containerPort }}
      nodePort: 30080
  type: NodePort
---
apiVersion: v1
kind: Service
metadata:
  name: db
  namespace: {{ .Values.namespace }}
  labels:
    app: db
spec:
  selector:
    app: devops-db
  ports:
    - name: db
      protocol: TCP
      port: {{ .Values.db.containerPort }}
      targetPort: {{ .Values.db.containerPort }}
  type: ClusterIP
